### ISSUE TITLE
关于S1中opencv安装的询问

### ISSUE THREAD

**Issue by superwyq** [nanmu42/robomasterpy#12]
请问一开始的pip安装opencv要在哪里输入，终端吗？如果是，该如何打开终端呢？
![image](https://user-images.githubusercontent.com/56257796/122665417-a3bb4680-d1d9-11eb-94e3-8ad39cb357a1.png)
请问下这个界面是怎么打开吗？
万分感谢

**Comment by nanmu42** [comment]
你好，

OpenCV需要单独安装：https://github.com/nanmu42/robomasterpy/blob/master/README.Chinese.md#%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96

命令在终端输入，终端的打开方式和系统有关，请自助查阅。

界面在执行程序后就会出现。
