### ISSUE TITLE
关于socket通信问题

### ISSUE THREAD

**Issue by superwyq** [nanmu42/robomasterpy#13]
通过commander自动获取IP地址会time out
使用固定IP地址进行连接会出现计算机积极拒绝，连接失败
附图
![image](https://user-images.githubusercontent.com/56257796/122677914-fcf59b00-d216-11eb-8d39-91cfc1c85da2.png)
![image](https://user-images.githubusercontent.com/56257796/122677931-10086b00-d217-11eb-9b99-87bd6be8d7a5.png)
IP地址没有错，ping得通，telnet常用端口不通。

**Comment by nanmu42** [comment]
你好，

你的设备是EP还是S1？

目前只有EP开放了TCP API，也就是说RobomasterPy只能支持到EP，S1的相关功能是被大疆锁定的，RobomasterPy作为第三方软件，无能为力。
