### ISSUE TITLE
系统依赖

### ISSUE THREAD

**Issue by Tie-1** [nanmu42/robomasterpy#19]
请问大佬，robomasterpy在windows系统下可以运行吗

**Comment by nanmu42** [comment]
和机甲交互那部分应该可以，框架那部分可能悬，依赖了Linux的信号。

**Comment by VickyCas** [comment]
> 和机甲交互那部分应该可以，框架那部分可能悬，依赖了Linux的信号。

感谢大佬！

**Comment by Tie-1** [comment]
> 和机甲交互那部分应该可以，框架那部分可能悬，依赖了Linux的信号。

请问大佬，robomasterpy可以运行在arm架构的计算平台吗？另外它对Ubuntu20.04是否适用呢

**Comment by nanmu42** [comment]
Ubuntu没问题，ARM可能需要自己编wheel，你可以用pip试试看。

OpenCV需要自己解决，因为有的喜欢conda的，有的喜欢pip的。
