### ISSUE TITLE
与官方robomaster的区别

### ISSUE THREAD

**Issue by Tie-1** [nanmu42/robomasterpy#20]
请问大佬写的robomasterpy和官方提供的robomaster包有什么区别呢

**Comment by nanmu42** [comment]
啊，区别是这个包比官方包出得还要早（狗头认真脸），另外带一个编程框架。

**Comment by Tie-1** [comment]
> 啊，区别是这个包比官方包出得还要早（狗头认真脸），另外带一个编程框架。

谢谢，非常感谢！看了您的github主页，有许多非常有意义的工作，为您点赞！

**Comment by nanmu42** [comment]
非常感谢你的赞许，祝你身体健康。
