### ISSUE TITLE
Sigwait is only supported on UNIX

### ISSUE THREAD

**Issue by siKruger** [nanmu42/robomasterpy#25]
https://github.com/nanmu42/robomasterpy/blob/master/robomasterpy/framework.py, Line 318
`signal.sigwait((signal.SIGINT, signal.SIGTERM))`

As per docs (https://docs.python.org/3/library/signal.html), sigwait is supported on Unix systems only. Therefor the library does not work on windows.

**Comment by nanmu42** [comment]
Thanks for the digging, I will update the doc as I don't have a working Windows environment.

A pull request would be very welcome.

**Comment by siKruger** [comment]
See #26 https://github.com/nanmu42/robomasterpy/pull/26

This makes it work on windows. I found no better solution than this one.

**Comment by nanmu42** [comment]
Closed via #26 .

Thanks a lot!
