### ISSUE TITLE
希望增加对机械臂的支持 / add support for robotic arm

### ISSUE THREAD

**Issue by GwenXD** [nanmu42/robomasterpy#6]
官方的 SDK 不支持 ARM，没办法在 Jetson Nano 上跑，看了你的框架感觉非常不错，希望可以增加对机械臂/爪的支持 : )

**Comment by nanmu42** [comment]
抱歉，我这边没有机械臂硬件，所以没有办法和动力进行开发和测试。也许你可以提一个PR让RobomasterPy变得更好。

在遇到未支持的命令时，你总是可以使用[`Commander.do()`](https://robomasterpy.nanmu.me/zh_CN/latest/api.html#robomasterpy.Commander.do)来自行实现，大疆官方的API文档在：https://robomaster-dev.readthedocs.io/zh_CN/latest/text_sdk/protocol_api.html#id55

祝你好运！

---

For English speakers:

Sorry I do not have the EP's robomatic arm, so I am unable to carry out development and test. A pull request would be appreciating.

When there is an unsupported method in RobomasterPy, you can always use [`Commander.do()`](https://robomasterpy.nanmu.me/en/latest/api.html#robomasterpy.Commander.do) to implement it by yourself, with DJI's API doc: https://robomaster-dev.readthedocs.io/en/latest/sdk/protocol_api.html#robotic-arm-control

Good luck!
